### ISSUE TITLE
Fail fast on lexing and parsing errors

### ISSUE THREAD

**Issue by crdoconnor** [durableOne/orgmunge#13]
I think it's possibly worth raising an exception [here](https://github.com/durableOne/orgmunge/blob/main/src/orgmunge/lexer.py#L36) and [here](https://github.com/durableOne/orgmunge/blob/main/src/orgmunge/parser.py#L198) according to the principle of [fail fast](https://en.wikipedia.org/wiki/Fail-fast).

Selfishly, Id like to be able to catch these errors and print an error message that fits in with the way the rest of the errors in my app are presented (i.e. not necessarily on the console, via print).

What do you think?

Personally I'd be keenly in favor of stricter parsing and a refusal to continue parsing if there are any lexer or parser errors and eliminating all print statement error messages. Thats what I did in my parsing library (strictyaml).

Once again, thanks for this library. I'm really starting to use it for a lot more stuff with orgzly and it's great!

**Comment by yantar92** [comment]
Not sure if it is relevant, but Org syntax cannot be invalid - if something does not match a particular syntax element, it is a paragraph.

**Comment by crdoconnor** [comment]
Ah I didn't know that.

**Comment by yantar92** [comment]
crdoconnor ***@***.***> writes:

> Ah I didn't know that.

You can find more at https://orgmode.org/worg/org-syntax.html#Paragraphs

-- 
Ihor Radchenko // yantar92,
Org mode contributor,
Learn more about Org mode at <https://orgmode.org/>.
Support Org development at <https://liberapay.com/org-mode>,
or support my work at <https://liberapay.com/yantar92>

**Comment by durableOne** [comment]
@crdoconnor I think that's a really good idea. Feel free to create a PR with it if I don't get to it fast enough

@yantar92 It's technically true that Org files never have syntax errors but this would make the parser too complicated for my ability and would also cause it to misinterpret an agenda file that was slightly mis-formatted, so in this case I prefer creating syntax/parsing errors where technically there are none. 
Another such choice I made is to not have headings "skip a level". For example, in Org files you can have headings of level 3 directly nested under headings of level 1 and Emacs will be perfectly happy with that but orgmunge will raise an exception if it encounters that condition because that structure doesn't make much sense from a logical standpoint (not to me at least).

**Comment by durableOne** [comment]
Completed. See https://github.com/durableOne/orgmunge/commit/cc5fa46618653bc024d27722ff4102829f9abc52
