### ISSUE TITLE
Programmically determine todo items

### ISSUE THREAD

**Issue by Nalisarc** [durableOne/orgmunge#3]
Looking over the project, I noticed that you use a json file to set the todo states currently.

This is something that can be set in the files metadata using a TODO header.
From what I've been looking at with the orgmode syntax it should be possible to scan for this and the fallback to a default if this option isn't set. 

The pattern would be something like:
```
# find "#+TODO:", mark as start;
# find next "\n", mark as end;
line = file.read(start : end)
line.split(" ")
line = line[1:] # omit heading
todo, done = line.split("|")

```
I'll look into this a bit more later.

**Comment by durableOne** [comment]
The reason I chose not to support this is because I can't see an easy way of letting the lexer know about the file it's parsing. And the lexer needs to know about the TODO tokens before lexing and parsing can start.

One way I'm thinking of improving this is to have a hierarchy of files: first, check the current directory for todos.json, then check the user's home, then check the package directory. This way, maybe we can have the Org class create todos.json on the fly if it finds a #+TODO line in the file or string passed to it.

**Comment by Nalisarc** [comment]
I figured you had your reasons!

From what I understand about how org files work the TODO header is only really used to define custom todo, done states on
a perfile basis. Mine are normally just TODO and DONE but I've seen a few variations.

To really work, I think it would need to hook into the users emacs instance somehow which is way outside of scope. 

Your idea of a hierarchy should work. I'd only have it create the todo.json file on the fly if a #+TODO: line exists. 
Otherwise it would fallback to defaults. Then having a specific argument that you could define when making the org object would be great. 

Once I have the tests up it should be easier to develop this feature.

**Comment by durableOne** [comment]
I'm marking this issue closed for now. I have implemented the hierarchy: the lexer looks for todos.json in the current directory, then your home directory, then finally in the package directory. Creating todos.json on the fly does not feel like an elegant solution to me: you'd have to save it in the current directory, making sure that you back up any existing todos.json file in the current directory and restore it after the parse is done.
I have experimented with different lexer states conditioned on detecting a '#+TODO' token but I think PLY doesn't let you implement a token definition rule dynamically, so that didn't work. Another solution would be to write our own lexer and make sure it's got the right methods to be compatible with the interface that the PLY parser is expecting. I, however, don't have the time (or the technical knowledge) to do this at the moment. Feel free to reopen this or create a PR if you decide to develop this feature.
